### ISSUE TITLE
Clustering with rmsd calculated for heavy (noh) atoms

### ISSUE THREAD

**Issue by MuhammadIIsmail** [tubiana/TTClust#15]
Can you provide the possible arguments for -sr? as I want to change it from the (default=backbone) to heavy atoms of both backbone and side chains.

Thank you.

**Comment by MuhammadIIsmail** [comment]
I mean by -sr the "selection syntax for RMSD"

**Comment by tubiana** [comment]
Hi!

The link to the selection syntax description on the readme is indeed broken, here's another link: http://mdtraj.org/1.9.3/atom_selection.html. 
I use the MDTRAJ selection syntax since I use this package for parsing and calculate the distance matrix :-) 

To select the heavy atoms of backbone and side-chain I would just select "protein and not type H" which will select all atoms (backbone and sidechain) excluding hydrogens
Best regard,
Thibault Tubiana.
