### ISSUE TITLE
Assigning x-axis (simulation time) in bar plots and generating distance matrix

### ISSUE THREAD

**Issue by MuhammadIIsmail** [tubiana/TTClust#17]
Dear Tubiana,

Thank you for your amazing TTClust program. 

First, I want to change the x-axis of the generated bar plots. It seems to count every 1000 frames as 1 ns, however, it may not be the case in my trajectory, so, how can I change it?

Second, the distance matrix is not generated with the other default figures, how can I generate it separately?

Thank you.

**Comment by tubiana** [comment]
Hi :-) 

Thank you for your feedback :-) 

>First, I want to change the x-axis of the generated bar plots. It seems to count every 1000 frames as 1 ns, however, it may not be the case in my trajectory, so, how can I change it?
When the trajectory don't have the 'unit' TTClust try to guess it, but I have to admit that it can be quite tricky sometimes and it can fail. 

> Second, the distance matrix is not generated with the other default figures, how can I generate it separately?
When I firstly developed TTClust, I had issues with distance matrices with bigger than 10000x10000. If you have more than 10000 frames, the matrix will not be generated.
 What is your trajectory size?

I can do the fixes within the day, but if you want to do it on your sources:
1. for the "ns" issue, time definition is between lines 780 to 794 on the last version. 
2. the limit for distance matrix is at line 10002

I can easily fix the limit for the distance matrix of course, but it can be more tricky for the time axis since It can be very specific of your trajectory...  I can maybe add a new option especially for that tho...

Best,
Thibault.

**Comment by MuhammadIIsmail** [comment]
Thank you for your reply :)

1. I could tailor the "ns" scale, thanks to your guidance.
2. I couldn't find the limit for distance matrix, as there is no line 10002. I would be thankful if you told me how to change it.

Thank you.
Ismail

**Comment by tubiana** [comment]
Oh sorry, my bad...
You have to change the limit `10002` at line 1085....
I will soon push an update were without limit for the distance matrix and with an user option to choose to keep "frame" :-) 
I will close this issue when the update is ready.

Best,
Thibault.

**Comment by tubiana** [comment]
Dear Ismail, 

I just pushed the new update, the version 4.7.4 with two new arguments added: 
 - `axis` to force "Frame" label in the barplot axis (use `-axis frame`)
 - `limitmat` to decrease the trajectory size limit to generate the distance matrix. It is now `100000000` but if the distance matrix is too long to generate, you can just decrease this limit with `-limitmat 10000`

I will close this issue now, don't hesitate to open it again if you have any question or issues :-) 

Best,
Thibault.
