### ISSUE TITLE
does water affect the clustering result?

### ISSUE THREAD

**Issue by hima111997** [tubiana/TTClust#19]
Greetings,

I have a question about TTClust. i use this command to cluster my MDS results.

ttclust -f file.dcd -t file.psf

but I noticed that at the end it gave me this 
<mdtraj.Trajectory with 250 frames, 174503 atoms, 54046 residues, and unitcells>

this number of atoms is the total number of atoms including water. 

So, will this affect the results? and if it affects, how can I solve it? 

Thanks

**Comment by tubiana** [comment]
Dear @hima111997,

Thank you for using TTClust 🙂

To answer your question, 2 selections arguments are very important for the clustering:
 - `-sa` which controls the trajectory alignment before the clustering.  
     it's important to align the trajectory before the clustering since it is based on the RMSD distance matrix. If you want to cluster on the protein and it moves on X-axis over time, you will have wrong results of course
 - `-sr` Which controls the selection for the RMSD distance matrix calculation (distance matrix used for clustering)

Both are the protein `backbone` per default. You can check [here](http://mdtraj.org/1.9.3/atom_selection.html) for atom selection language. So with just your command (`ttclust -f file.dcd -t file.psf`) the clustering will be made only on the backbone of protein. Even if in the output PDBs you have water.

Also, you have a last argument `-st` if you want to save only one selection of the trajectory in your PDB clusters (example `-st protein` will only save the protein in the PDB)

One last thing, from experience the auto clustering function has a tendency to underestimate the number of clusters (I think...) Since the number of clusters always depends on the system and, the user as well, of course, it's not a bad idea to first run the auto clustering function to get the dendrogram (https://github.com/tubiana/TTClust#dendrogram) and then check if the system can be more clusterized 🙂. 

I suggest you to look at the TTClust argument with `ttclust -h` as well as the readme (from the [atom selection](https://github.com/tubiana/TTClust#atoms-selection)) to have a better understanding on how TTClust works and to be sure your clustering is correct 🙂

Best regards,  
Thibault Tubiana.

**Comment by hima111997** [comment]
Thank you for this deep explanation. However, I have a question. the default method for determining the number of clusters is the elbow method and from my experience (which is very little with unsupervised machine learning) elbow method is a good way for selecting the number of clusters. So why does it have a tendency to underestimate the number of clusters? 

Also, how can I determine the optimum number of clusters to produce from a dendrogram (I mean which cutoff I should select)?

Thank you

**Comment by tubiana** [comment]
You are welcome :-) Thank you also for your feedback on the elbow method, it comforts me in my decision to implement it. 
> So why does it tend to underestimate the number of clusters?  

Here it's only "according to me", I always prefer to have a higher number of clusters with smaller sub-populations (but it's because I'm always afraid to miss a "breakthrough" conformation XD)

> Also, how can I determine the optimum number of clusters to produce from a dendrogram (I mean which cutoff I should select)?

It always depends on the user and how far you want to cluster (and how similar you want your clusters to be). 
It can be a little hard in the beginning, and of course, the distance values depend on your system but let's take this dendrogram from google image: 
![dendrogram](https://cdn.xlstat.com/img/tutorials/cahmx6f.gif)

We can easily find 5 big clusters with a hierarchical distance of ~32.  Some will be quite okay with 5 major clusters, but personally, I like to study subpopulations as well, so I will cut at ~25 to have 9 clusters. It can be quite "guesstimate." 🙂 
I cannot confirm it, but I think the elbow method will give 5 clusters because the similarity between 9 clusters will be too high. 

When I use TTClust, I use the auto clustering function (that will use the KMeans method to find `X` as the optimal number of cluster (between 2 to 15) and then execute a hierarchical clustering with `X` clusters output). 
And then from the dendrogram produced, I will visually evaluate if I can have more cluster or if it is useless :-)

**Comment by hima111997** [comment]
Thank you again for this explanation. So it depends on the user himself to select the cut off distance.
And thank you for this excellent tool.

**Comment by tubiana** [comment]
You are welcome 🙂
