### ISSUE TITLE
Ligand poses clustering 

### ISSUE THREAD

**Issue by Marwa-Abdelkader** [tubiana/TTClust#27]
If I want to cluster the ligand poses instead of the protein backbone , should I select it from -sa, -sr, or -st?

**Comment by tubiana** [comment]
Hi ! 

`-sr` is for calculating the RMSD matrix (used for the clustering) and `-sa` is the selection for the alignment of the trajectory. So this is a good question because depending the alignment of the trajectory, your will observe very different things. 

1. If you use `-sa "resname LIG" -sr "resname LIG"` you will aligned the trajectory on the ligand and compute the trajectory on the ligand. It means that you will cluster your trajectory based on the  **atomic fluctuations** of the ligand.
2. But if you use `-sa "backbone" -sr "resname LIG"`, you keep the alignement on the protein and you will cluster on the ligand pose. This could be a bias if you just want to cluster the differents conformation of your ligand, but it will be more accurate for ligand pose. Because the ligand position will be different if your take as reference the protein.  

To summary:
-  Atomic fluctuation of the ligand (local fluctuation, fragment fluctuation) -> Alignment on the ligand `-sa "resname LIG" -sr "resname LIG"`
- How the ligand move in the protein -> Alignment on the protein `-sa "backbone" -sr "resname LIG"`

Best regards,
Thibault.

**Comment by Marwa-Abdelkader** [comment]
> Hi !
> 
> `-sr` is for calculating the RMSD matrix (used for the clustering) and `-sa` is the selection for the alignment of the trajectory. So this is a good question because depending the alignment of the trajectory, your will observe very different things.
> 
> 1. If you use `-sa "resname LIG" -sr "resname LIG"` you will aligned the trajectory on the ligand and compute the trajectory on the ligand. It means that you will cluster your trajectory based on the  **atomic fluctuations** of the ligand.
> 2. But if you use `-sa "backbone" -sr "resname LIG"`, you keep the alignement on the protein and you will cluster on the ligand pose. This could be a bias if you just want to cluster the differents conformation of your ligand, but it will be more accurate for ligand pose. Because the ligand position will be different if your take as reference the protein.
> 
> To summary:
> 
> * Atomic fluctuation of the ligand (local fluctuation, fragment fluctuation) -> Alignment on the ligand `-sa "resname LIG" -sr "resname LIG"`
> * How the ligand move in the protein -> Alignment on the protein `-sa "backbone" -sr "resname LIG"`
> 
> Best regards,
> Thibault.

Thank you so much for the clarification and for that very useful tool :)

**Comment by tubiana** [comment]
You're welcome :) 

Feel free to open a ticket again if you have any issues.
