### ISSUE TITLE
The representative frame

### ISSUE THREAD

**Issue by Jameel9** [tubiana/TTClust#30]
Hello Sir

I hope you're well 

I have a trajectory from GROMACS for a single protein. When I did clustering based on specific range of residues, I noticed that the representative frame of Cluster 1 is actually a frame within the cluster 2. 
Is it possible?

Thnx

**Comment by tubiana** [comment]
Hi Jameel!

I think I fixed a bug like this long time ago.... It was a difference of +1 or -1 because of the shift with the Python indexing system which is 0-based.
Which version do you use ? Can you provide output in the logfile (for your 2 clusters), the difference is in the logfile or the saved representative frame ?

Please be reassured that this error should only be the label of the logfile or the PDB file. The representative frame will be the real representative frame since in the code, the index of the frame is kept for each cluster and this same index is used to save the frame. 

Best,
Thibault.

**Comment by Jameel9** [comment]
I am using the version 4.10.1.

In the log file (attached below), it says that the representative frame for cluster 1 is the frame no. 424. but the saved frame is number 425 (which is fine as this frame is within the first cluster). Is the additional frame resulted from the alignment with the input reference frame in the topology file? 


[TTClust.log](https://github.com/tubiana/TTClust/files/7956926/TTClust.log)

**Comment by tubiana** [comment]
Sorry for the delay, i'm very busy lately...

The frame saved is 424, the error is only on the filename (cf. this code).
```
    traj[frame].save_pdb("{}/C{}-f{}-s{}.pdb".format(logname,
                                                     cluster_num,
                                                     frame + 1,  # +1 to get the 1 index based frame
                                                     size))
```
This is a leftover from a bug fixed some time ago. 
I will remove the `+1` and push all updates on Github, PiPy and conda, hopefully, today, I will close this issue when it's done :)

Best,
Thibault.

**Comment by tubiana** [comment]
Took me long time just for 1 Line to change.. Sorry I forgot about that. This is done. I made the change in the logfile instead of the file (the file was okay after reviewing the issue)
