### ISSUE TITLE
ttclust.py:726: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix

### ISSUE THREAD

**Issue by hackerzone85** [tubiana/TTClust#31]
Hello Sir,
I hope you're well
Thank you for such a nice tool for clustering traj frames.
While using this tool using the following command
```
ttclust -f md_0_200ns_noPBC_noWAT_noION.xtc -t first_frame.pdb -st "protein" -sr "name CA" -m average
```
I am getting this warning
> ttclust.py:726: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix

Why I am getting this warning?
Whether this is ignorable?
To understand this warning, I search on google and found this https://stackoverflow.com/questions/60817473/warning-uncondensed-distance-matrix-in-python

**Comment by tubiana** [comment]
Same again sorry, I was really busy and forget this repo a bit...
It may be due to wrong packages version. The matrix is still square so it is not an uncondensed distance matrix. However some users reported this issue when they use other packages version

I close this for now since it's old, don't hesitate to open it again if you still have this error, and add all your packages version number if you can :)
