### ISSUE TITLE
selection of heavy atoms of a ligand 

### ISSUE THREAD

**Issue by qasimpars** [tubiana/TTClust#34]
Hi,

I  want to cluster the five docking poses of a ligand based on the RMSD of only heavy atoms of the ligand. What should I select for `-sr`?
Please note that it should calculate the RMSDs for only heavy atoms of the ligand and I wouldn't align the ligand on the protein. I think I should select `none` for `-sa`?

Best,

**Comment by tubiana** [comment]
Hi! 

Disclamer first : TTClust has not been made to cluster so small molecules and especially so small number of sample...
Basically you use clustering to reduce hundred of frames from an MD to 5 to 10. 
I would use TTClust to cluster 5 docking pause since you already have a small number of sample. 

Howerver, still want to do clustering on MD base on protein-ligand system, `none` for `-sa` will deactivate the alignement and use the raw trajectory.  So if you want to compare the docking pause, it depends if your trajectory is already pre-aligned on the protein (because I guess you don't want to compare the ligand conformation, but docking poses **relative** to the protein).
Otherwise `-sa backbone` will align the trajectory of the backbone of the protein, use your heavy atoms name in `-sr` to cluster on the ligand. You can help yourself with this: https://mdtraj.org/1.9.4/atom_selection.html#reference

Best,
